[tool.black]
line-length = 88
target-version = ["py310"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

[tool.pylint."MESSAGES CONTROL"]
disable = [
  "invalid-name",
  "too-few-public-methods",
  "too-many-arguments",
  "too-many-locals",
  "too-many-positional-arguments",
  "missing-function-docstring",
  "missing-module-docstring",
  "duplicate-code" # TODO: Refactor duplicate-code in train_optuna_rf.py
]

[tool.pylint.'MAIN']
init-hook = 'import sys; from pathlib import Path; sys.path.insert(0, str(Path(".").resolve()))'

[tool.pytest.ini_options]
filterwarnings = [
  "ignore::DeprecationWarning:mlflow.*",
  "ignore::DeprecationWarning:pkg_resources.*",
  "ignore::DeprecationWarning:pydantic.*"
]

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
show_missing = true