{
 "title": "Model Monitoring Dashboard",
 "time": { "from": "2025-07-07T14:38:48.745Z", "to": "2025-07-07T18:02:17.441Z" },
 "panels": [
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  (report_json->>'timestamp')::timestamp AS ts,\n  (report_json->'metrics'->'missing_values'->>'share_of_missing_values')::float AS missing_share\nFROM evidently_reports\nORDER BY ts\n"
    }
   ]
  },
  {
   "title": "Data Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  (report_json->>'timestamp')::timestamp AS ts,\n  (report_json->'metrics'->'dataset_drift'->>'dataset_drift')::float AS drift_score\nFROM evidently_reports\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Drifted features",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  (report_json->>'timestamp')::timestamp AS ts,\n  (report_json->'metrics'->'dataset_drift'->>'n_drifted_features')::int AS drifted_features\nFROM evidently_reports\nORDER BY ts"
    }
   ]
  }
 ]
}