data_paths:
  raw_data: data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
  processed_data: data/processed/clean.csv
  split_data_dir: data/split/
  train_data: data/split/train.csv
  val_data: data/split/val.csv
  test_data: data/split/test.csv

data_params:
  target: Churn
  test_size: 0.2
  val_size: 0.2
  random_state: 42

model_registry:
  name: rf-optuna-model
  stage: None

monitoring:
  evidently_report_html: reports/evidently_drift_report.html
  evidently_report_json: reports/evidently_drift_report.json
