name: CI

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Check formatting with black
        run: black --check src/ tests/

      - name: Check import order with isort
        run: isort --check-only src/ tests/
      
      - name: Lint with pylint
        run: |
          pylint src/ tests/

      - name: Run tests
        run: |
          pytest
      
      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=term --cov-report=xml

      - name: Generate coverage badge
        run: |
          mkdir -p badges
          coverage-badge -o badges/coverage.svg -f

      - name: Upload badge as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: badges/coverage.svg

      # Optional — авто-коміт бейджа (вимагає налаштування git user/token)
      - name: Commit coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "GitHub Action"
          git add badges/coverage.svg
          git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
          git push
    
